Update openrc related tooling now that auth has been removed from vendordata (#38)
* Update openrc related tooling now that auth has been removed from vendordata

* Don't swallow auth url

* Update help text

* Fix bug creating ec2 creds when setting up the rclone object store mount

diff --git a/elements/cc-rclone/bin/setup-cc-mount-object-store b/elements/cc-rclone/bin/setup-cc-mount-object-store
--- a/elements/cc-rclone/bin/setup-cc-mount-object-store
+++ b/elements/cc-rclone/bin/setup-cc-mount-object-store
@@ -11,33 +11,32 @@ trap 'exit_failure' EXIT
 set -e
 
 if [ ! -f /home/cc/openrc ]; then
-    OPENRC=$(cc-read-vendordata "openrc")
-    if [ "${OPENRC}" != "null" ]; then
-        cc-read-vendordata "openrc" > /home/cc/openrc
-        sed -i 's/^ *//g' /home/cc/openrc
-    else
-        echo "$(date '+%Y-%m-%d %H:%M:%S'): Unable to read OPENRC" >> /home/cc/cc_my_mounting_point.failure
-        exit 1
-    fi
+    echo "No ~/openrc found. Run 'ccauth openrc --output ~/openrc' to authenticate, then re-run this script." >&2
+    echo "$(date '+%Y-%m-%d %H:%M:%S'): No ~/openrc found, run 'ccauth openrc --output ~/openrc' first" >> /home/cc/cc_my_mounting_point.failure
+    exit 1
 fi
 
 source /home/cc/openrc
+
+REGION=$(cc-read-vendordata "region")
+if [ "${REGION}" = "KVM@TACC" ]; then
+    echo "$(date '+%Y-%m-%d %H:%M:%S'): KVM@TACC does not have an object store available" >> /home/cc/cc_my_mounting_point.failure
+    exit 1
+fi
+
+OS_STORAGE_URL=$(openstack catalog show object-store -f json | jq -r '.endpoints[] | select(.interface=="public") | .url')
 if [ -z "${OS_STORAGE_URL}" ]; then
-    echo "$(date '+%Y-%m-%d %H:%M:%S'): OS_STORAGE_URL was not set" >> /home/cc/cc_my_mounting_point.failure
-    REGION=$(cc-read-vendordata "region")
-    if [ "${REGION}" = "KVM@TACC" ]; then
-        echo "$(date '+%Y-%m-%d %H:%M:%S'): KVM@TACC does not have an object store available" >> /home/cc/cc_my_mounting_point.failure
-    fi
+    echo "$(date '+%Y-%m-%d %H:%M:%S'): Unable to look up object-store endpoint" >> /home/cc/cc_my_mounting_point.failure
     exit 1
 fi
 
 EC2_STORAGE_ENDPOINT=${OS_STORAGE_URL%/swift*}
-EC2_CREDS="$(openstack ec2 credential list -f json 2>/dev/null)"
-if [ $? -eq 0 ] && [ ! -z "$output" ]; then
-    ACCESS_KEY=$(echo "$output" | jq -r '.[0].Access')
-    SECRET_KEY=$(echo "$output" | jq -r '.[0].Secret')
+EC2_CREDS="$(openstack ec2 credential list -f json)"
+if [ $? -eq 0 ] && [ ! -z "$EC2_CREDS" ] && [ "$(echo "$EC2_CREDS" | jq 'length')" -gt 0 ]; then
+    ACCESS_KEY=$(echo "$EC2_CREDS" | jq -r '.[0].Access')
+    SECRET_KEY=$(echo "$EC2_CREDS" | jq -r '.[0].Secret')
 else
-    EC2_CREDS="$(openstack ec2 credential create -f json 2>/dev/null)"
+    EC2_CREDS="$(openstack ec2 credential create -f json)"
     ACCESS_KEY=$(echo ${EC2_CREDS} | jq -r '.access')
     SECRET_KEY=$(echo ${EC2_CREDS} | jq -r '.secret')
 fi
